apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/balsmn/crispy-doodle:{{.VERSION}}"
  artifacts:
  - imageName: balsmn/crispy-doodle:1.0.0-SNAPSHOT
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/balsmn/crispy-doodle:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: crispy-doodle
        chartPath: charts/crispy-doodle
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/balsmn/crispy-doodle"
          image.tag: "{{.DIGEST_HEX}}"
